GET http://localhost:3001/api/persons

###

# Functioning get
GET http://localhost:3001/api/persons/61becfcd001352f02980e610

###
# Malformed id
GET http://localhost:3001/api/persons/41be8bdaaa0431f

###
# 404 Not Found
GET http://localhost:3001/api/persons/61be8bdaaa0431f993454589

###

DELETE http://localhost:3001/api/persons/61becfcd001352f02980e610

###
# Malformed id
DELETE http://localhost:3001/api/persons/69be8d10aa1f0416cf034155

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Matti Virtanen",
    "number": "040-5231309"
}

###

PUT http://localhost:3001/api/persons/61bed43ec39a5009a07b6e07
Content-Type: application/json

{
    "name": "Mika Waltari",
    "number": "00002"
}